platform :ios, '8.0'

source 'git@github.com:CocoaPods/Specs.git'

target 'WeexDemo' do
  pod 'Masonry', '~> 1.1.0'
  pod 'WeexSDK'
  pod 'WXDevtool'
  pod 'SDWebImage'
	pod 'Toast', '~> 4.0.0'
	pod 'AFNetworking', '~> 3.2.1'
end
